dist: trusty
sudo: required
language: c
services:
  - docker
script:
  - docker build -t kissrobert/gcf-ci .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push kissrobert/gcf-ci;
    fi
